### ISSUE TITLE
NEP 50 adoptation

### ISSUE THREAD

**Issue by MFaisalZaki** [pyrddlgym-project/pyRDDLGym#257]
Hi, I'm trying to run the tutorial example, and I got this error:

![Screenshot from 2024-08-22 12-40-43](https://github.com/user-attachments/assets/22d87b63-2a31-490c-b562-66f1781d8bee)

To reproduce:
```
import pyRDDLGym
env = pyRDDLGym.make("Cartpole_Continuous_gym", "0")
```

**Comment by ataitler** [comment]
Hi, 
Can you please share which version of python do have installed?

Ayal

**Comment by MFaisalZaki** [comment]
It is version 2.0.
![Screenshot from 2024-08-22 17-06-16](https://github.com/user-attachments/assets/4a703c19-7381-4fb7-a68c-55546e6d60a2)

**Comment by ssanner** [comment]
I believe Ayal was asking about your version of Python, not PyRDDLGym.

In any event, please see the link "pyRDDLGym playground" at the bottom of
the following page

  https://pyrddlgym-project.github.io/AAAI24-lab

for a Google Colab that can successfully run "Cartpole_Continuous_gym"
using the default Colab **Python version 3.10**.

**Comment by MFaisalZaki** [comment]
My bad; the Python version I'm running is 3.10.12 inside a virtual environment.

![Screenshot from 2024-08-23 10-42-37](https://github.com/user-attachments/assets/37af2090-7138-4336-9bbb-34e944f8255c)

**Comment by ssanner** [comment]
The issue is likely with the numpy version; I note that the working Google
Colab example referenced in this thread is using numpy 1.26.4.

In general, I would encourage you to differentiate your installation from
the working Google Colab example to understand what package versions are
leading to your errors.

When you get it working, we'd appreciate knowing which package version
changes were required as this may help other users.  Thanks!

**Comment by ataitler** [comment]
Hi @MFaisalZaki, I am glad to hear everything is working now.
Yes we are aware of version problems both with numpy and python 3.12.x.
We will of course update the requirements file.
