### ISSUE TITLE
Invalid action error

### ISSUE THREAD

**Issue by MFaisalZaki** [pyrddlgym-project/pyRDDLGym#258]
Hi, I am trying the MarsRover domain, and I got this error even though I am using the `env.action_space.sample()`
![Screenshot from 2024-09-03 12-59-02](https://github.com/user-attachments/assets/49b843ab-4e51-4976-925d-f2cc653c8f84)

Here is the code to reproduce:
```
import pyRDDLGym
env = pyRDDLGym.make('MarsRover_ippc2023', '0')
env.reset()
env.step(env.action_space.sample())
```

On the side, it fails when I try to import an agent.
```
from pyRDDLgym.core.policy import RandomAgent
agent = RandomAgent(action_space=env.action_space, num_actions=env.max_allowed_actions)
```

![Screenshot from 2024-09-03 13-00-50](https://github.com/user-attachments/assets/8a4ec568-6bc2-4722-b40a-40c9d7fe95e1)

**Comment by mike-gimelfarb** [comment]
Hi,

[note: I am on vacation and thus my ability to debug is currently limited].

For the first code block, this is intended behavior. You should always use the Agent implementations provided by pyrddlgym (RandomAgent, NoopAgent, or any valid subclass of BaseAgent) rather than the gym spaces for sampling because additional processing and checking of the sampled action arrays is required by the pyrddlgym simulator, which the gym spaces do not provide. 

Your second code block is correct but it seems you mistyped the package name, i.e. pyRDDLGym not pyRDDLgym) - python is case sensitive. If that does not resolve the error, please ensure you have the latest pyRDDLGym installed, and if still doesn't work, please report back. Thanks.

**Comment by mike-gimelfarb** [comment]
I've gone back to the docs and it seems the error is on us... we have this typo there too! Thanks for bringing that to our attention ;)
