### ISSUE TITLE
[Question] Forward simulation

### ISSUE THREAD

**Issue by MFaisalZaki** [pyrddlgym-project/pyRDDLGym#259]
I know that the library is aimed at RL-based planners. Is there any plan to support forward simulation that allows us to implement A*-based and MCTS planners? There is this project called [plangym](https://plangym.readthedocs.io/en/latest/) that provides such functionality, but it does not account for RDDL.

**Comment by ssanner** [comment]
Note: We're absolutely happy to answer questions about pyRDDLGym, but I
would encourage general questions to go to the Discussions
<https://github.com/orgs/pyrddlgym-project/discussions> section.

pyRDDLGym is designed to support planners and compilations to different
target languages used by a variety of planning methodologies.  You can find
a number of out-of-the-box planners (including the PROST MCTS
<https://github.com/pyrddlgym-project/pyRDDLGym-prost> planner for discrete
RDDL domains) as sub-repositories of the top-level
<https://github.com/pyrddlgym-project> of the project.

It's important to note that pyRDDLGym can generally model stochastic
discrete & continuous state and action MDPs (and POMDPs).  Deterministic,
discrete search methodologies such as A* would not readily apply in
expressive stochastic, continuous MDPs (and this is why PROST MCTS only
supports a discrete subset of RDDL).  That said, we do provide planners for
these more expressive continuous cases such as JaxPlan
<https://github.com/pyrddlgym-project/pyRDDLGym-jax> (a gradient-based
planner) and GurobiPlan
<https://github.com/pyrddlgym-project/pyRDDLGym-gurobi> (a mixed integer
optimization-based planner).  All sub-repositories have linked readthedocs
documentation (linked under "About") and for further reading, here is a
recent paper discussing JaxPlan and GurobiPlan
<https://ssanner.github.io/papers/icaps24_jaxplan.pdf>.

**Comment by ssanner** [comment]
Note: We're absolutely happy to answer questions about pyRDDLGym, but I would encourage general questions to go to the [Discussions](https://github.com/orgs/pyrddlgym-project/discussions) section.

pyRDDLGym is designed to support planners and compilations to different target languages used by a variety of planning methodologies.  You can find a number of out-of-the-box planners (including the [PROST MCTS](https://github.com/pyrddlgym-project/pyRDDLGym-prost) planner for discrete RDDL domains) as sub-repositories of the [top-level](https://github.com/pyrddlgym-project) of the project.

It's important to note that pyRDDLGym can generally model stochastic discrete & continuous state and action MDPs (and POMDPs).  Deterministic, discrete search methodologies such as A* would not readily apply in expressive stochastic, continuous MDPs (and this is why PROST MCTS only supports a discrete subset of RDDL).  That said, we do provide planners for these more expressive continuous cases such as [JaxPlan](https://github.com/pyrddlgym-project/pyRDDLGym-jax) (a gradient-based planner) and [GurobiPlan](https://github.com/pyrddlgym-project/pyRDDLGym-gurobi) (a mixed integer optimization-based planner).  All sub-repositories have linked readthedocs documentation (linked under "About") and for further reading, here is a recent [paper discussing JaxPlan and GurobiPlan](https://ssanner.github.io/papers/icaps24_jaxplan.pdf).

**Comment by mike-gimelfarb** [comment]
Thanks @ssanner for an excellent discussion and limitations!

Actually, there are progressive widening (PW) and other continuous-space extensions of MCTS that we've had some interest in exploring further, but we don't have the bandwidth currently for pushing in that (very nontrivial) direction.

In case you are looking to implement your own code using pyRDDLGym as a foundation (or perhaps building a wrapper for pyRDDLGym to interface with existing PW-MCTS methods) and need a head start to see how it can interface with pyRDDLGym, you may want to look at this very simple [prototype](https://github.com/pyrddlgym-project/pyRDDLGym/blob/version_1.4.4_stable/pyRDDLGym/Core/Jax/JaxRDDLBackpropPlannerUCT.py) we wrote for v1.4.4 (which was subsequently removed because it is very nontrivial to scale and tune such algorithms for complex problems).

**Comment by MFaisalZaki** [comment]
Thanks @mike-gimelfarb. This sounds interesting. I will have a look and see what I can do with it.

**Comment by mike-gimelfarb** [comment]
I'm afraid I cannot answer this question because we did not do a lot of testing of that code, and hence why it was removed from the final version. I believe it was successful at solving the easier problems, such as cart-pole and Wildfire, although it would likely need a lot more tricks for complex problems. You may wish to check out the [PROST planner](https://ai.dmi.unibas.ch/papers/keller-eyerich-icaps2012.pdf) and the tricks they use as a source of inspiration for leveraging the structure of the problem in an intelligent way, as well as the [docker wrapper for pyRDDLGym](https://github.com/pyrddlgym-project/pyRDDLGym-prost). The simple MCTS code we had did not leverage any of these tricks.
